export const ENV = {
  SUPABASE_URL: 'https://cnoeumcshfrfrzyvbxcn.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNub2V1bWNzaGZyZnJ6eXZieGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNzIzNDEsImV4cCI6MjA5NTg0ODM0MX0.Sm2-IvEjvIQKwVDbj91jKf87QSonHWlqHBGeFqMuSr8',
  ADMIN_PASSWORD_HASH: '__ADMIN_PASSWORD_HASH__'
};